# .github/workflows/deploy.yml

name: Deploy to RailWay

# on:
#   push:
#     branches: [ main ]
on: workflow_dispatch # 임시 - 수동 트리거로 사용

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Railway 배포
        uses: railway-app/railway-github-action@v1
        with:
          railway-token: ${{ secrets.RAILWAY_TOKEN }}
